spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          fetch_size: 400
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
  datasource:
    hikari:
      auto-commit: false
  threads:
    virtual:
      enabled: false
  application:
    name: perftest
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  profiles:
    active: spanner-remote