spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

#gcloud compute ssh alloydb-proxy --zone=europe-central2-c -- -L 5432:172.20.128.2:5432 -N -f